print("number \t\t Square\t\t  Cube")
print("1 \t\t",str(1*1)," \t\t ",str(1**3))
print("2 \t\t",str(2*2)," \t\t ",str(2**3))
print("3 \t\t",str(3*3)," \t\t ",str(3**3))
print("4 \t\t",str(4*4)," \t\t ",str(4**3))
print("5 \t\t",str(5*5)," \t\t ",str(5**3))
print("6 \t\t",str(6*6)," \t\t ",str(6**3))